<?php

namespace App\Models;

use App\Events\DocumentRegistered;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Score extends Model
{
    use HasFactory;
    protected $guarded = [];
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::created(function (Score $score){
            event(new DocumentRegistered($score));
        });
    }
    public function content(): BelongsTo
    {
        return $this->belongsTo(Content::class);
    }
    protected $casts = [
        'score' => 'float',
    ];

}
